//
//  AWSConfiguration.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.8
//
//

import AWSCore


// Cognito User Pools Identity Id
let AWSCognitoUserPoolId: String = "ap-northeast-1_mrSyebNbF"

// Cognito User Pools App Client Id
let AWSCognitoUserPoolAppClientId: String = "5b926jto0khr8m52n70pjth89l"

// Cognito User Pools Region
let AWSCognitoUserPoolRegion: AWSRegionType = .apNortheast1

// Cognito User Pools Client Secret
let AWSCognitoUserPoolClientSecret: String = "1p00l9ktl8hnifk47tsoi9ejpnga59ejhdl6ragp7ufrt1ki21h6"
