//
//  Days.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.8
//

import Foundation
import UIKit
import AWSDynamoDB

class Days: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _dayId: NSNumber?
    var _category: String?
    var _durationSeconds: NSNumber?
    var _subcategory: String?
    
    class func dynamoDBTableName() -> String {

        return "ledaapp-mobilehub-99797186-days"
    }
    
    class func hashKeyAttribute() -> String {

        return "_dayId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_dayId" : "day_id",
               "_category" : "category",
               "_durationSeconds" : "duration_seconds",
               "_subcategory" : "subcategory",
        ]
    }
}
