//
//  Goals.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.8
//

import Foundation
import UIKit
import AWSDynamoDB

class Goals: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _week: NSNumber?
    var _goalTitle: String?
    
    class func dynamoDBTableName() -> String {

        return "ledaapp-mobilehub-99797186-goals"
    }
    
    class func hashKeyAttribute() -> String {

        return "_week"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_week" : "week",
               "_goalTitle" : "goal_title",
        ]
    }
}
