//
//  Tasks.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.8
//

import Foundation
import UIKit
import AWSDynamoDB

class Tasks: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _contentDay: NSNumber?
    var _sort: NSNumber?
    var _durationSeconds: NSNumber?
    var _taskCategory: String?
    var _taskData: [String: Any]?
    var _taskSubcategory: String?
    var _taskTitle: String?
    var _taskType: String?
    
    
    class func dynamoDBTableName() -> String {
        
        return "ledaapp-mobilehub-99797186-tasks"
    }
    
    class func hashKeyAttribute() -> String {
        
        return "_contentDay"
    }
    
    class func rangeKeyAttribute() -> String {
        
        return "_sort"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
            "_contentDay" : "content_day",
            "_sort" : "sort",
            "_durationSeconds" : "duration_seconds",
            "_taskCategory" : "task_category",
            "_taskData" : "task_data",
            "_taskSubcategory" : "task_subcategory",
            "_taskTitle" : "task_title",
            "_taskType" : "task_type",
        ]
    }
}
