//
//  UserToolStatus.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.8
//

import Foundation
import UIKit
import AWSDynamoDB

class UserToolStatus: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _breathingUnlocked: NSNumber?
    var _complexEmotionsUnlocked: NSNumber?
    var _makingMeaningUnlocked: NSNumber?
    
    class func dynamoDBTableName() -> String {

        return "ledaapp-mobilehub-99797186-user_tool_status"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_breathingUnlocked" : "breathing_unlocked",
               "_complexEmotionsUnlocked" : "complex_emotions_unlocked",
               "_makingMeaningUnlocked" : "making_meaning_unlocked",
        ]
    }
}
